author: Harald Husum
title: Harahu
email: harald.husum@gmail.com
description: >-
  Not much here yet, unfortunaly. But stay tuned!
url: "https://harahu.github.io"
repository: "harahu/harahu.github.io"
twitter_username: harahudev
github_username:  harahu

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

