author: Harald Husum
title: Harahu
email: harald.husum@gmail.com
description: >-
  Not much here yet, unfortunaly. But stay tuned!
baseurl: "/harahu.github.io/"
url: "https://harahu.github.io"
repository: "harahu/harahu.github.io"
twitter_username: harahudev
github_username:  harahu

# Build settings
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
   - Gemfile
   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
